# Goals for this Notebook
- master data split 70% train, 15% val 15% test 
- save .csv to Google Drive (https://drive.google.com/drive/folders/1jHSmyPs9_1Z8JgiNfZCjJ_BhSnar5rAZ?usp=drive_link)
- Initial EDA

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# Ensure plots display inline in the notebook
%matplotlib inline

In [2]:
# Load csv and set up df
csv_path = '../data/raw/emscad_dataset.csv'
df = pd.read_csv(csv_path)
print(df.head())

                                       title            location department  \
0                           Marketing Intern    US, NY, New York  Marketing
1  Customer Service - Cloud Video Production      NZ, , Auckland    Success
2    Commissioning Machinery Assistant (CMA)       US, IA, Wever        NaN
3          Account Executive - Washington DC  US, DC, Washington      Sales
4                        Bill Review Manager  US, FL, Fort Worth        NaN

  salary_range                                    company_profile  \
0          NaN  <h3>We're Food52, and we've created a groundbr...
1          NaN  <h3>90 Seconds, the worlds Cloud Video Product...
2          NaN  <h3></h3>\r\n<p>Valor Services provides Workfo...
3          NaN  <p>Our passion for improving quality of life t...
4          NaN  <p>SpotSource Solutions LLC is a Global Human ...

                                         description  \
0  <p>Food52, a fast-growing, James Beard Award-w...
1  <p>Organised - Focused - Vibrant - Awesome!<br...
2  <p>Our client, located in Houston, is actively...
3  <p><b>THE COMPANY: ESRI – Environmental System...
4  <p><b>JOB TITLE:</b> Itemization Review Manage...

                                        requirements  \
0  <ul>\r\n<li>Experience with content management...
1  <p><b>What we expect from you:</b></p>\r\n<p>Y...
2  <ul>\r\n<li>Implement pre-commissioning and co...
3  <ul>\r\n<li>\r\n<b>EDUCATION: </b>Bachelor’s o...
4  <p><b>QUALIFICATIONS:</b></p>\r\n<ul>\r\n<li>R...

                                            benefits telecommuting  \
0                                                NaN             f
1  <h3><b>What you will get from us</b></h3>\r\n<...             f
2                                                NaN             f
3  <p>Our culture is anything but corporate—we ha...             f
4                       <p>Full Benefits Offered</p>             f

  has_company_logo has_questions employment_type required_experience  \
0                t             f           Other          Internship
1                t             f       Full-time      Not Applicable
2                t             f             NaN                 NaN
3                t             f       Full-time    Mid-Senior level
4                t             t       Full-time    Mid-Senior level

  required_education                   industry              function  \
0                NaN                        NaN             Marketing
1                NaN  Marketing and Advertising      Customer Service
2                NaN                        NaN                   NaN
3  Bachelor's Degree          Computer Software                 Sales
4  Bachelor's Degree     Hospital & Health Care  Health Care Provider

  fraudulent in_balanced_dataset
0          f                   f
1          f                   f
2          f                   f
3          f                   f
4          f                   f

### Understandting the dataset

In [3]:
print('\n Important Information on our dataset')
print("="*50)
df.info()

print("\n" + "="*50)
print("Statistical Summary:")
print("="*50)
display(df.describe()) # Added display() to show the statistical summary

print("\n" + "="*50)
print("Null Summary:")
print("="*50)
display(df.isnull().sum())

 Important Information on our dataset
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17880 entries, 0 to 17879
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   title                17880 non-null  object
 1   location             17534 non-null  object
 2   department           6333 non-null   object
 3   salary_range         2868 non-null   object
 4   company_profile      14572 non-null  object
 5   description          17880 non-null  object
 6   requirements         15191 non-null  object
 7   benefits             10684 non-null  object
 8   telecommuting        17880 non-null  object
 9   has_company_logo     17880 non-null  object
 10  has_questions        17880 non-null  object
 11  employment_type      14409 non-null  object
 12  required_experience  10830 non-null  object
 13  required_education   9775 non-null   object
 14  industry             12977 non-null  object
 15  function             11425 non-null  object
 16  fraudulent           17880 non-null  object
 17  in_balanced_dataset  17880 non-null  object
dtypes: object(18)
memory usage: 2.5+ MB

==================================================
Statistical Summary:
==================================================

,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent,in_balanced_dataset
count,17880,17534,6333,2868,14572,17880,15191,10684,17880,17880,17880,14409,10830,9775,12977,11425,17880,17880
unique,11231,3105,1337,874,1710,15095,12119,6510,2,2,2,5,7,13,131,37,2,2
top,English Teacher Abroad,"GB, LND, London",Sales,0-0,<p>We help teachers get safe &amp; secure jobs...,"<p>Play with kids, get paid for it </p>\r\n<p>...",<p>University degree required. TEFL / TESOL / ...,<p>See job description</p>,f,t,f,Full-time,Mid-Senior level,Bachelor's Degree,Information Technology and Services,Information Technology,f,f
freq,311,718,551,142,726,376,410,726,17113,14220,9088,11620,3809,5145,1734,1749,17014,16980

==================================================
Null Summary:
==================================================

title                      0
location                 346
department             11547
salary_range           15012
company_profile         3308
description                0
requirements            2689
benefits                7196
telecommuting              0
has_company_logo           0
has_questions              0
employment_type         3471
required_experience     7050
required_education      8105
industry                4903
function                6455
fraudulent                 0
in_balanced_dataset        0
dtype: int64

### Master Data Split
- The df was split using a stratified-y, which was the target variable being 'Fraudeulent'
- This is necessary since there is an imbalance between the fraudelent listings and the legitimate ones.

In [4]:
from sklearn.model_selection import train_test_split

# Define your target variable 
target_col = 'fraudulent' 

# First split: 70% Train, 30% Remainder [Stratified]
train_df, rem_df = train_test_split(
    df, 
    train_size=0.7, 
    random_state=42, 
    stratify=df[target_col]  # <--- Project-critical change
)

# Second split: Split remainder equally (15% Val, 15% Test) [Stratified]
val_df, test_df = train_test_split(
    rem_df, 
    test_size=0.5, 
    random_state=42, 
    stratify=rem_df[target_col] # <--- Stratify based on the remainder's labels
)

print(f"Train: {len(train_df)} | Val: {len(val_df)} | Test: {len(test_df)}")

Train: 12516 | Val: 2682 | Test: 2682

In [6]:
# Save train, test, val to .csv
train_df.to_csv('../data/processed/train.csv', index=False)
val_df.to_csv('../data/processed/val.csv', index=False)
test_df.to_csv('../data/processed/test.csv', index=False)

print("Files saved to data/processed/")

Files saved to data/processed/

In [9]:
df.head()

,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent,in_balanced_dataset
0,Marketing Intern,"US, NY, New York",Marketing,NaN,"<h3>We're Food52, and we've created a groundbr...","<p>Food52, a fast-growing, James Beard Award-w...",<ul>\r\n<li>Experience with content management...,NaN,f,t,f,Other,Internship,NaN,NaN,Marketing,f,f
1,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"<h3>90 Seconds, the worlds Cloud Video Product...",<p>Organised - Focused - Vibrant - Awesome!<br...,<p><b>What we expect from you:</b></p>\r\n<p>Y...,<h3><b>What you will get from us</b></h3>\r\n<...,f,t,f,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,f,f
2,Commissioning Machinery Assistant (CMA),"US, IA, Wever",NaN,NaN,<h3></h3>\r\n<p>Valor Services provides Workfo...,"<p>Our client, located in Houston, is actively...",<ul>\r\n<li>Implement pre-commissioning and co...,NaN,f,t,f,NaN,NaN,NaN,NaN,NaN,f,f
3,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,<p>Our passion for improving quality of life t...,<p><b>THE COMPANY: ESRI – Environmental System...,<ul>\r\n<li>\r\n<b>EDUCATION: </b>Bachelor’s o...,<p>Our culture is anything but corporate—we ha...,f,t,f,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,f,f
4,Bill Review Manager,"US, FL, Fort Worth",NaN,NaN,<p>SpotSource Solutions LLC is a Global Human ...,<p><b>JOB TITLE:</b> Itemization Review Manage...,<p><b>QUALIFICATIONS:</b></p>\r\n<ul>\r\n<li>R...,<p>Full Benefits Offered</p>,f,t,t,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,f,f